dofile("wifi_config.lua")
dofile("wifi_setup.lua")
dofile("display_setup.lua")
dofile("draw.lua")

dofile("connect_station.lua")
connect_station()
dofile("publish_weather.lua")
dofile("update_maxtemp.lua")
dofile("update_maxhumi.lua")
dofile("update_mintemp.lua")
dofile("update_minhumi.lua")
dofile("publish_maxtemp.lua")
dofile("publish_maxhumi.lua")
dofile("publish_mintemp.lua")
dofile("publish_minhumi.lua")
dofile("update_time.lua")
dofile("update_display.lua")
dofile("update_weather.lua")
dofile("server.lua")

